version: '3.8'

services:
  ppt-translator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ppt-translator-mcp
    environment:
      - DEFAULT_TARGET_LANGUAGE=${DEFAULT_TARGET_LANGUAGE:-ko}
      - BEDROCK_MODEL_ID=${BEDROCK_MODEL_ID:-us.anthropic.claude-3-7-sonnet-20250219-v1:0}
      - MAX_TOKENS=${MAX_TOKENS:-4000}
      - TEMPERATURE=${TEMPERATURE:-0.1}
      - ENABLE_POLISHING=${ENABLE_POLISHING:-true}
      - DEBUG=${DEBUG:-false}
    volumes:
      # Mount current directory for PowerPoint files
      - .:/app/workspace
      # Mount AWS credentials from host system
      - ~/.aws:/home/appuser/.aws:ro
    working_dir: /app
    # Keep container running for testing
    command: ["tail", "-f", "/dev/null"]
    # Uncomment below to run the MCP server directly
    # command: ["uv", "run", "python", "fastmcp_server.py"]
